E-Shop/Controllers/EShopController.cs
using E_Shop.Data.Interfaces;
using E_Shop.Data.Models;
using E_Shop.Models;
using E_Shop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace E_Shop.Controllers
{
	public class EShopController : Controller
	{
		private readonly ILogger<EShopController> _logger;
		private readonly IProductRepository _productRepository;
		private readonly ICategoryRepository _categoryRepository;

		public EShopController(ILogger<EShopController> logger, ICategoryRepository categoryRepository,IProductRepository productRepository)
		{
			_logger = logger;
			_productRepository = productRepository;
			_categoryRepository = categoryRepository;
		}

		

		public ViewResult List(int categoryId)
		{
			IEnumerable<Product> products;
			string currentCategory=string.Empty;
			if(categoryId <= 0)
			{
				products= _productRepository.Products;
				currentCategory = "All Products";
			}else
			{
                products = _productRepository.Products.Where(p => p.Category.CategoryId == categoryId).OrderBy(p =>p.ProductId);
				var category= _categoryRepository.GetCategories.FirstOrDefault(c => c.CategoryId == categoryId);
				currentCategory = category.CategoryName;

            }
			var productListViewModel = new ProductListViewModel
			{
				Products=products,	
				CurrentCategory=currentCategory,
			};
			return View(productListViewModel);


		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

E-Shop/Views/Shared/Components/CategoryMenu/Default.cshtml
<div class="dropdown">
    <a class="nav-link dropdown-toggle text-white" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
     Category List
    </a>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
         @foreach (var category in Model)
        {
            <a class="dropdown-item" asp-controller="EShop" asp-action="List"
               asp-route-categoryId="@category.CategoryId">@category.CategoryName</a>
      

        }
        <a class="dropdown-item" asp-controller="EShop" asp-action="List" asp-route-category="0">View all products</a>
       
    </div>
</div>






@* <li class="dropdown">
    <a 
       class="dropdown-toggle" data-toggle="dropdown">Products<b class="caret"></b></a>
    <ul class="dropdown-menu">
        @foreach (var category in Model)
        {
            <li>
                <a asp-controller="EShop" asp-action="List"
                   asp-route-categoryId="@category.CategoryId">@category.CategoryName</a>
            </li>
        }
        <li class="divider"></li>
        <li>
            <a asp-controller="EShop" asp-action="List" asp-route-category="0">View all products</a>
        </li>
    </ul>
</li> *@