E-Shop/ViewModels/ShoppingCartViewModel.cs
using E_Shop.Data.Models;

namespace E_Shop.ViewModels
{
    public class ShoppingCartViewModel
    {
        public ShoppingCart ShoppingCart { get; set; }
        public decimal ShoppingCartTotal { get; set; }
    }
}

E-Shop/Controllers/OrderController.cs
using Microsoft.AspNetCore;
using E_Shop.Data.Interfaces;
using E_Shop.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace E_Shop.Controllers
{
	public class OrderController : Controller
	{
		private readonly IOrderRepository _orderRepository;
		private readonly ShoppingCart _shoppingCart;

        public OrderController(IOrderRepository orderRepository,ShoppingCart shoppingCart	)
        {
			_orderRepository = orderRepository;
			_shoppingCart = shoppingCart;
            
        }
		public IActionResult Checkout()
		{
			return View();
		}

            [HttpPost]
        public IActionResult Checkout(Order order)
		{
			var items = _shoppingCart.GetShoppingCartItems();
			_shoppingCart.ShoppingCartItems = items;
			if (_shoppingCart.ShoppingCartItems.Count == 0)
			{
				ModelState.AddModelError("", "Your cart is empty, add some products first");

			}
            if (ModelState.IsValid)
            {
				_orderRepository.CreateOrder(order);
				_shoppingCart.ClearCart();
				return RedirectToAction("CheckoutComplete");
			}
			return View(order);
		}
		public IActionResult CheckoutComplete() 
		{
			ViewBag.CheckoutCompleteMessage = "Thanks for your order!:) ";
			return View();
		}

		public IActionResult ViewOrder()
		{
			var result=_orderRepository.GetUserOrder();
			return View(result);
		}
		 public   IActionResult OrderDetails(int orderId)
		{
			var orderDetails =  _orderRepository.GetOrderDetails(orderId);
			return View(orderDetails);
		}

		public IActionResult CancleOrder(int orderId)
		{
			_orderRepository.CancelOrder(orderId);
			return RedirectToAction("ViewOrder");

		}
	}
}

E-Shop/Controllers/ShoppingCartController.cs
using E_Shop.Data.Interfaces;
using E_Shop.Data.Models;
using E_Shop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace E_Shop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ShoppingCart _shoppingCart;
        public ShoppingCartController(IProductRepository productRepository,ShoppingCart shoppingCart)
        {
            _productRepository = productRepository;
            _shoppingCart = shoppingCart;
            
        }
        public ActionResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var sCVM = new ShoppingCartViewModel
            {
                ShoppingCart=_shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal(),
            };
            return View(sCVM);

        }
        public  RedirectToActionResult AddToShoppingCart(int productId)
        {
            var selectProduct=_productRepository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (selectProduct != null)
            {
                _shoppingCart.AddToCart(selectProduct,1);
            }
            return RedirectToAction("Index","Home");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int productId)
        {
            var selectProduct = _productRepository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (selectProduct != null)
            {
                _shoppingCart.RemoveFromCart(selectProduct);
            }
            return RedirectToAction("Index");
        }

       

    }
}

E-Shop/Views/ShoppingCart/Index.cshtml
@model ShoppingCartViewModel
@{
    ViewData["Title"] = "Shopping Cart";
}

<div class="text-center">

 

    <div class="row checkoutForm">
        <h2>Your shopping cart</h2>
        <h4>Here are the products in your shopping cart.</h4>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Selected amount</th>
                    <th>Product</th>
                    <th class="text-right">Price</th>
                    <th class="text-right">Subtotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
                {
                    <tr>
                        <td class="text-center">@line.Amount</td>
                        <td class="text-left">@line.Product.Name</td>
                        <td class="text-right">@line.Product.Price.ToString("c")</td>
                        <td class="text-right">
                            @((line.Amount * line.Product.Price).ToString("c"))
                        </td>
                        <td class="text-center"><a class="btn btn-sm btn-danger" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-productId="@line.Product.ProductId">Remove</a></td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-right">Total:</td>
                    <td class="text-right">
                        @Model.ShoppingCartTotal.ToString("c")
                    </td>
                </tr>
            </tfoot>
        </table>

        <div class="text-right">
           
            <div class="btn-group ">
               
                <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
              
              
            </div>
        </div>
    </div>
   

   
</div>